import * as vscode from 'vscode';
import { StateController } from '../../stateController';

/**
 * Generates AI agent documentation files (CLAUDE.md, AGENTS.md) in the .codereader/ directory.
 * These files describe JSON data structures so that AI agents can properly read/modify the data.
 *
 * Generation conditions:
 * - Only in workspace storage mode (not extension storage)
 * - Only when .codereader/ directory already exists
 * - Skipped if existing file version matches current extension version
 */
export class AgentDocsGenerator {
    constructor(
        private stateController: StateController,
        private version: string
    ) {}

    /**
     * Generate documentation files if needed.
     * This is non-blocking and safe to call during activation.
     */
    async generateIfNeeded(): Promise<void> {
        // Only generate in workspace storage mode
        if (!this.stateController.isWorkspaceStorage()) {
            console.log('Agent docs: skipped (not workspace storage mode)');
            return;
        }

        const storageUri = this.stateController.getStorageUri();
        if (!storageUri) {
            return;
        }

        // Only generate if .codereader/ directory already exists
        try {
            await vscode.workspace.fs.stat(storageUri);
        } catch {
            console.log('Agent docs: skipped (.codereader/ directory does not exist yet)');
            return;
        }

        // Check if regeneration is needed (version mismatch or file missing)
        const claudeMdUri = vscode.Uri.joinPath(storageUri, 'CLAUDE.md');
        if (!await this.needsRegeneration(claudeMdUri)) {
            console.log('Agent docs: skipped (version matches)');
            return;
        }

        // Generate and write documentation
        const content = this.generateContent();
        const agentsMdUri = vscode.Uri.joinPath(storageUri, 'AGENTS.md');

        await Promise.all([
            this.writeFile(claudeMdUri, content),
            this.writeFile(agentsMdUri, content),
        ]);

        console.log('Agent docs: generated CLAUDE.md and AGENTS.md (version: ' + this.version + ')');
    }

    /**
     * Check if the file needs regeneration by comparing version stamps.
     */
    private async needsRegeneration(fileUri: vscode.Uri): Promise<boolean> {
        try {
            const fileData = await vscode.workspace.fs.readFile(fileUri);
            const content = new TextDecoder().decode(fileData);
            const match = content.match(/<!-- codereader-version: (.+?) -->/);
            if (match && match[1] === this.version) {
                return false;
            }
        } catch {
            // File doesn't exist - needs generation
        }
        return true;
    }

    /**
     * Write content to a file using VS Code filesystem API.
     */
    private async writeFile(uri: vscode.Uri, content: string): Promise<void> {
        await vscode.workspace.fs.writeFile(uri, new TextEncoder().encode(content));
    }

    /**
     * Generate the full Markdown documentation content.
     */
    private generateContent(): string {
        return `<!-- codereader-version: ${this.version} -->
<!-- This file is auto-generated by the CodeReader extension. Manual edits will be overwritten on next launch. -->

# CodeReader Data Documentation

This directory contains data files for the CodeReader VS Code extension.
The extension provides code reading assistance tools: PostIt notes, QuickMemo, CodeMarker, and ReadTracker.

> **Important**: The extension monitors file changes via mtime. If you edit JSON files while VS Code is running, the extension will automatically reload the data on next access.

---

## File Overview

| File | Description |
|---|---|
| \`postIt.json\` | Code-attached sticky notes with folder organization |
| \`quickMemo.json\` | Quick markdown memos with file linking |
| \`codeMarker.json\` | Code diagnostics, line highlights, and syntax highlights |
| \`readTracker.json\` | File reading progress tracking |
| \`quickMemo/\` | Directory containing QuickMemo \`.md\` files |

---

## postIt.json

Sticky notes attached to specific code locations.

### Schema

\`\`\`typescript
{
    PostIts: {
        [folder: string]: PostItNote[]
    },
    Config: {
        debug: boolean,
        lastedFolder?: string       // Last used folder name
    },
    Version: string                 // "1.0.0"
}

interface PostItNote {
    id: string                      // Unique ID: Date.now() + random base36
    title: string                   // Note title
    color: string                   // Color name (e.g., "yellow", "red")
    Lines: PostItLine[]             // Code locations this note is attached to
    ViewType: "line" | "codelens"   // Display mode
    createdAt: string               // ISO 8601 datetime
    updatedAt: string               // ISO 8601 datetime
}

interface PostItLine {
    file: string                    // Absolute file path
    line: number                    // Start line number (1-indexed)
    endLine: number                 // End line number (1-indexed)
    text: string                    // Code snippet text
}
\`\`\`

### Default Data

\`\`\`json
{
    "PostIts": {
        "Default": []
    },
    "Config": {
        "debug": false
    },
    "Version": "1.0.0"
}
\`\`\`

### Constraints

- The \`"Default"\` folder must always exist and cannot be renamed or deleted
- Note IDs are generated as \`Date.now().toString() + Math.random().toString(36).substring(2)\`
- \`file\` in PostItLine uses absolute file paths
- \`ViewType\` must be either \`"line"\` or \`"codelens"\`

---

## quickMemo.json

Quick markdown memos with optional file linking. Actual memo content is stored as \`.md\` files in the \`quickMemo/\` subdirectory.

### Schema

\`\`\`typescript
{
    QuickMemos: {
        [folder: string]: QuickMemoFile[]
    },
    Config: {
        debug: boolean,
        lastedFolder?: string       // Last used folder name
    },
    Version: string                 // "1.0.0"
}

interface QuickMemoFile {
    id: string                      // UUID (crypto.randomUUID())
    title: string                   // Display title
    file: string                    // Markdown filename (e.g., "uuid.md") in quickMemo/ dir
    Lines: QuickMemoLine[]          // Linked workspace files
    linkedLine?: QuickMemoLine      // Line the memo was created from
    createAt: string                // ISO 8601 datetime
    updateAt: string                // ISO 8601 datetime
}

interface QuickMemoLine {
    file: string                    // Absolute file path
    line: number                    // Line number (0-indexed internally)
    endLine?: number                // Optional end line
    text: string                    // Code snippet text
}
\`\`\`

### Default Data

\`\`\`json
{
    "QuickMemos": {
        "General": []
    },
    "Config": {
        "debug": false,
        "lastedFolder": "General"
    },
    "Version": "1.0.0"
}
\`\`\`

### Constraints

- The \`"General"\` folder must always exist and cannot be renamed or deleted
- Memo IDs are UUIDs generated via \`crypto.randomUUID()\`
- The \`file\` field references an \`.md\` file in the \`quickMemo/\` subdirectory
- Each \`.md\` file must exist on disk; deleting a memo should also delete its \`.md\` file
- \`linkedLine.line\` is 0-indexed internally (displayed as 1-indexed in UI)
- Note: field names are \`createAt\`/\`updateAt\` (not \`createdAt\`/\`updatedAt\`)

---

## codeMarker.json

Code diagnostics, line highlights, and syntax highlights organized by folder and file.

### Schema

\`\`\`typescript
{
    CodeMarker: {
        [folder: string]: {
            [filePath: string]: {
                Diagnostics: CodeMarkerDiagnostics[],
                LineHighlight: CodeMarkerLineHighlight[],
                SyntaxHighlight: CodeMarkerSyntaxHighlight | null
            }
        }
    },
    Config: {
        debug: boolean,
        lastedFolder?: string       // Last used folder name
    },
    Version: string                 // "1.0.0"
}

interface CodeMarkerDiagnostics {
    id: string                      // Unique ID: Date.now().toString(36) + random
    type: "hint" | "info" | "warning" | "error"
    text: string                    // Diagnostic message
    Lines: {
        startLine: number           // 1-indexed
        endLine: number             // 1-indexed
        startColumn: number         // 1-indexed
        endColumn: number           // 1-indexed
        text: string                // Code snippet
    }
    createdAt: string               // ISO 8601 datetime
    updatedAt: string               // ISO 8601 datetime
}

interface CodeMarkerLineHighlight {
    id: string                      // Unique ID
    color: string                   // Highlight color
    Lines: {
        startLine: number           // 1-indexed
        endLine: number             // 1-indexed
    }[]
    type?: "manual" | "readTracker" // Source of highlight
    createdAt: string               // ISO 8601 datetime
    updatedAt: string               // ISO 8601 datetime
}

interface CodeMarkerSyntaxHighlight {
    id: string                      // Unique ID
    color: string                   // Highlight color
    Lines: number[]                 // Array of line numbers (1-indexed)
    createdAt: string               // ISO 8601 datetime
    updatedAt: string               // ISO 8601 datetime
}
\`\`\`

### Default Data

\`\`\`json
{
    "CodeMarker": {
        "Default": {}
    },
    "Config": {
        "debug": false
    },
    "Version": "1.0.0"
}
\`\`\`

### Constraints

- The \`"Default"\` folder must always exist and cannot be renamed or deleted
- Diagnostics IDs are generated as \`Date.now().toString(36) + Math.random().toString(36).substr(2)\`
- The second-level keys are absolute file paths
- Each file entry contains arrays for Diagnostics and LineHighlight, and a nullable SyntaxHighlight
- \`type\` values for Diagnostics must be one of: \`"hint"\`, \`"info"\`, \`"warning"\`, \`"error"\`
- \`LineHighlight.type\` of \`"readTracker"\` indicates the highlight was auto-generated by ReadTracker

---

## readTracker.json

Tracks which lines of code have been read in each file.

### Schema

\`\`\`typescript
{
    Records: {
        [filePath: string]: ReadRecord
    },
    Config: {
        debug: boolean,
        weekStartsOnMonday: boolean // true: Monday, false: Sunday
    },
    Version: string                 // "1.0.0"
}

interface ReadRecord {
    id: string                      // Unique ID: "read_" + timestamp-based
    filePath: string                // Workspace-relative file path
    lines: ReadLineRange[]          // List of read line ranges
    createdAt: string               // ISO 8601 datetime
    updatedAt: string               // ISO 8601 datetime
}

interface ReadLineRange {
    startLine: number               // 1-indexed
    endLine: number                 // 1-indexed
    markedAt: string                // ISO 8601 datetime (when this range was marked as read)
}
\`\`\`

### Default Data

\`\`\`json
{
    "Records": {},
    "Config": {
        "debug": false,
        "weekStartsOnMonday": true
    },
    "Version": "1.0.0"
}
\`\`\`

### Constraints

- Record keys and \`filePath\` values are workspace-relative paths (via \`vscode.workspace.asRelativePath()\`)
- Line ranges are 1-indexed
- All timestamps use ISO 8601 format (strings, not Date objects)
- IDs are generated as \`"read_" + Date.now().toString(36) + Math.random().toString(36).substring(2)\`

---

## Common Rules

### Folder Management
- Folder paths use \`/\` as separator for nesting (e.g., \`"Work/Bugs/Critical"\`)
- Each tool has a default folder that cannot be deleted or renamed:
  - PostIt: \`"Default"\`
  - QuickMemo: \`"General"\`
  - CodeMarker: \`"Default"\`
- Creating a nested folder auto-creates parent folders
- \`Config.lastedFolder\` must reference an existing folder key

### Version and Config
- Do not modify the \`Version\` field
- \`Config.debug\` should remain \`false\` unless debugging
- Preserve all \`Config\` fields when modifying data

### ID Generation
- PostIt: \`Date.now().toString() + Math.random().toString(36).substring(2)\`
- QuickMemo: \`crypto.randomUUID()\` (UUID v4)
- CodeMarker: \`Date.now().toString(36) + Math.random().toString(36).substr(2)\`
- ReadTracker: \`"read_" + Date.now().toString(36) + Math.random().toString(36).substring(2)\`

### Timestamps
- PostIt, QuickMemo, CodeMarker: Serialized as ISO 8601 strings in JSON (originally Date objects)
- ReadTracker: Stored as ISO 8601 strings explicitly

### File Paths
- PostIt, CodeMarker: Absolute file paths
- QuickMemo \`linkedLine\`: Absolute file paths
- ReadTracker: Workspace-relative paths
`;
    }
}
